name: Deploy Sanity
on:
  push:
    branches: [main]
jobs:
  sanity-deploy:
    runs-on: ubuntu-18.04
    defaults:
      run: 
        working-directory: studio
    name: Deploy Sanity
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Install Sanity CLI
        run: npm install @sanity/cli
      - name: Deploy Sanity Studio
        run: echo hannaogbjoernbryllup | npx sanity deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
